version: '3.8'
services:
  generator:
    image: 'ghcr.io/cloud-technology/project-generator/project-generator:2'
    ports:
      - '8080:8080'

  database: # https://hub.docker.com/_/postgres
    image: 'postgres:14.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: 'pw123456'
      POSTGRES_DB: 'devdb'