version: '3.8'
services:

  redis: # https://hub.docker.com/_/redis
    image: 'redis:7.0.2'
    restart: always
    command: >
          --requirepass "pw123456"
    ports:
      - '6379:6379'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

  postgres: # https://hub.docker.com/_/postgres
    image: 'postgres:14.3-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: 'pw123456'
      POSTGRES_DB: 'devdb'
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '2'
